---
title: "ggplot2 Brushing"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r}
library(ggplot2)
library(readxl)
library(dplyr)
library(shiny)

dados <- read_xlsx("Atividade1_TI4A-1.xlsx")
dados <- rename(dados, idade = Q1, freqCell = Q7)

```

```{r}
selectedData <- reactive({
  data <- brushedPoints(dados, input$plot_brush)
  if (nrow(data) == 0) {
    data <- dados  
  }
  data
})
```

Column {data-width=300}
-----------------------------------------------------------------------
### Frequência de Uso de Celular por Idade

```{r}
renderPlot({
  ggplot(data = dados, aes(x = idade, y = freqCell, color = idade)) + 
    geom_jitter(size = 3, alpha = 0.7) + 
    labs(title = "Frequência de uso de celular por idade",
         x = "Idade",
         y = "Frequência de uso de celular",
         color = "Idade") +  
    theme_minimal()
}, outputArgs = list(brush = brushOpts(id = "plot_brush")))
```

```{r}
renderTable({
  selectedData()  # Display the selected data
})
```

### Distribuição de Idade dos Participantes

```{r, echo=FALSE}
renderPlot({
  ggplot(selectedData(), aes(x = idade, fill = factor(Q3))) + 
    geom_bar() + 
    labs(title = "Distribuição de Idade dos Participantes", 
         x = "Idade", 
         y = "Número de Participantes") +
    theme_minimal()
})
```

Column {data-height=100, data-width=300}
-----------------------------------------------------------------------
### Distribuição de Idade dos Participantes

```{r}
renderPlot({
  ggplot(selectedData(), aes(x = Q13, y = Q14, fill = Q14)) +
    geom_boxplot(alpha = 0.7, color = "#007bff") +
    labs(
      title = "Frequência de Uso de Apps de Jogos", 
      x = "Escala de 1 a 100",
      y = "Frequência de Uso"
    ) +
    scale_fill_manual(values = c("Sempre" = "#007bff", "Frequentemente" = "#00bfae", "Às vezes" = "#ff6f61", "Quase Nunca" = "#d9534f")) + 
    theme_minimal(base_size = 15) + 
    theme(
      panel.grid.major = element_line(color = "grey80", size = 0.5),  
      panel.grid.minor = element_blank(),  
      plot.title = element_text(face = "bold", size = 18), 
      legend.title = element_text(face = "bold"),
      legend.position = "right"
    )
})
```


